spring:
  application:
    name: zuul-gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

server:
  port: 8888

zuul:
  routes:
    files-manager:
      path: /api/v1/manager/**
      service-id: files-manager-service
    meta-info:
      path: /api/v1/meta-info/**
      service-id: meta-info-service

